### ISSUE TITLE
Exclude directories

### ISSUE THREAD

**Issue by langston-barrett** [veniversum/git-visualizer#9]
Is there/could there be a way to exclude directories? Many golang projects have a `vendor/` directory that includes the source for all of their build dependencies (usually far larger than the rest of the project). For an example, checkout `hashicorp/consul`.

**Comment by veniversum** [comment]
As of now, directories can be collapsed by clicking on the node. It could be rather inconvenient as you would have to look for the node first. 

`hashicorp/consul` with /vendor/ node collapsed:
![image](https://cloud.githubusercontent.com/assets/6357330/14620061/a437f674-05b2-11e6-9006-05197e85f29c.png)

Any suggestions as to how this feature can be implemented?

**Comment by veniversum** [comment]
You can now pass in an exclude parameter to specify (a comma delimited list of) directories to collapse on load.

E.g. http://veniversum.me/git-visualizer/?owner=hashicorp&repo=consul&exclude=vendor,watch
